BMNC_PROJECT/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import loginlogout.urls as loginlogout
import lihatprofile.urls as profile
import lihatpolling.urls as lihat_polling
import tambah_berita.urls as berita
import buat_polling.urls as polling
import homepage.urls as home
import register.urls as register

urlpatterns = [
    url(r'^profile/', include(('lihatprofile.urls','profile'), namespace='profile')),
    url(r'^lihat-polling/', include(('lihatpolling.urls','lihat_polling'), namespace='lihat-polling')),
    url(r'^berita/', include(('tambah_berita.urls','berita'), namespace='berita')),
    url(r'^polling/', include(('buat_polling.urls','polling'), namespace='polling')),
	url(r'^homepage/', include(('homepage.urls','home'), namespace='home')),
    url(r'^register/', include(('register.urls','register'), namespace='register')),
    url(r'^$', include(('homepage.urls','home'), namespace='home'))
    ]

homepage/urls.py
from django.conf.urls import url
from .views import *

#url for app

urlpatterns = [
    url(r'^$', show_home, name='showHome'),
]

register/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.db import connection

# Create your views here.

response = {}

def show_home(request):
    return render_to_response('bmnc-homescreen.html')

# Create your views here.
def index(request):
	cursor = connection.cursor()
	cursor.execute('select * from berita')
	berita = cursor.fetchall()    
	print (berita)
	response['judul_berita'] = berita[0][1]
	response['judul_berita_1'] = berita[1][1]
	response['judul_berita_2'] = berita[2][1]

	cursor.execute('select * from riwayat')
	riwayat = cursor.fetchall()    
	print (riwayat)
	response['isi_berita'] = riwayat[0][3]
	response['isi_berita_1'] = riwayat[1][3]
	response['isi_berita_2'] = riwayat[2][3]

	return render_to_response('bmnc-register.html')

homepage/templates/bmnc-homescreen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap csss -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>
        BMNC Project
    </title>
    <style>
    * 

    #footer {
      text-align: center;
    }

    #prof-img {
      width: 60%;
      height: 60%;
      padding-top: 20px;
    }

    #link-title {
      font-weight: lighter;
    }

    #nav-profile {
      color: white;
    }

    #nav-forum {
      color: white;
    }

    #forum-btn , #search-btn {
    display: inline-block;
    margin: 10px;
    border: 2px solid #000000;
    background-color: black;
    color: white;
  }

  #forum-btn:hover, #search-btn:hover {
    background-color: white;
    color: black;
  }

    .link-url {
      width: 40%;
      margin: 10px;
    }

    .navbar {
      background-color: #175676;
    }

    .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 800px;
    margin: auto;
    text-align: center;
    }

   

    li {
      color: white;
    }

    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
    }

    a {
        text-decoration: none;
        font-size: 15px;
        color: black;
    }

    button:hover {
        background: none;
        border: 2px solid #000000;
        color: black;
    }

    a:hover {
      opacity: 0.7;
    }

    </style>
</head>

<body>
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container" id="header-bg">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a id="home-title" class="navbar-brand" href="{% url 'profile:index' %}">BMNC Project</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <!-- LINK MENUJU table, dan link menuju home#form -->
              <li><a id="nav-profile" href="{% url 'berita:index' %}"> Berita </a></li>
              <li><a id="nav-forum" href="{% url 'lihat-polling:index' %}"> Polling </a> </li>
              <li><a id="nav-forum" href="{% url 'profile:index' %}"> Profil </a> </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    </header>
    <content>
        <div class="container">
          <h2>Selamat Datang di BMNC!</h2>
          <hr/>
          <section name="bio">
            <div class="card">
              <img id="prof-img" src="https://media.wsls.com/photo/2017/04/24/Whats%20News%20Today_1493062809311_9576980_ver1.0_1280_720.png" style="width:60% height:60%">
              <h1 class="lead" >Ayo bergabung di BMNC!</h1>
              <a href="#" class="btn btn-secondary btn-lg active link-url" id="forum-btn" role="button" aria-pressed="true">
              Login
              <small class="text-muted">(Pengguna Lama)</small>
              </a>
              <a href="{% url 'register:index' %}" class="btn btn-secondary btn-lg active link-url" id="search-btn" role="button" aria-pressed="true">
              Registrasi
              <small class="text-muted">(Pengguna Baru)</small>
              </a>
              <p><button>Contact</button></p>
              </div>
          </section>
          <hr/>
        </div>
    </content>
    <footer>
        <p id="footer">&copy; Group 18 Basdat 2018-1 | Hardcode </p>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>