BMNC_PROJECT/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import loginlogout.urls as loginlogout
import lihatprofile.urls as profile
import lihatpolling.urls as lihat_polling
import tambah_berita.urls as berita
import buat_polling.urls as polling
import homepage.urls as home
import register.urls as register

urlpatterns = [
    url(r'^profile/', include(('lihatprofile.urls','profile'), namespace='profile')),
    url(r'^lihat-polling/', include(('lihatpolling.urls','lihat_polling'), namespace='lihat-polling')),
    url(r'^berita/', include(('tambah_berita.urls','berita'), namespace='berita')),
    url(r'^polling/', include(('buat_polling.urls','polling'), namespace='polling')),
	url(r'^homepage/', include(('homepage.urls','home'), namespace='home')),
    url(r'^register/', include(('register.urls','register'), namespace='register')),
    url(r'^$', include(('homepage.urls','home'), namespace='home'))
    ]

buat_polling/urls.py
from django.conf.urls import url
from .views import *

#url for app
urlpatterns = [
    url(r'^buat_polling_berita', buat_polling_berita, name='buat_polling_berita'),
    url(r'^buat_polling_biasa', buat_polling_biasa, name='buat_polling_biasa'),
    url(r'^submit_polling_berita', submit_polling_berita, name='submit_polling_berita'),
    url(r'^submit_polling_biasa', submit_polling_biasa, name='submit_polling_biasa'),
]

homepage/urls.py
from django.conf.urls import url
from .views import *

#url for app

urlpatterns = [
    url(r'^$', show_home, name='showHome'),
]

lihatpolling/urls.py
from django.conf.urls import url
from .views import index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),

]

lihatpolling/views.py
from django.shortcuts import render
from django.db import connection
# Create your views here.


def index(request):
	response = {}
	cursor = connection.cursor()
	cursor.execute('select * from polling_biasa')
	polling_biasa = cursor.fetchall()    
	print (polling_biasa)
	response['pertanyaan_polling'] = polling_biasa[0][2]
	response['pertanyaan_polling_1'] = polling_biasa[1][2]
	response['pertanyaan_polling_2'] = polling_biasa[2][2]

	cursor.execute('select * from polling')
	polling = cursor.fetchall()    
	print (polling)
	response['start_at'] = polling[0][1]
	response['start_at_1'] = polling[1][1]
	response['start_at_1'] = polling[2][1]
	response['end_at'] = polling[0][2]
	response['end_at_1'] = polling[1][2]
	response['end_at_2'] = polling[2][2]

	return render(request, 'polling.html', response)

lihatpolling/templates/polling.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="HandheldFriendly" content="true">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
  <link rel="stylesheet" href="{% static  'css/bootstrap-social.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <style>
         #nav-profile {
          color: white;
        }

        #nav-forum {
          color: white;
        }

        .navbar {
          background-color: #175676;
        }
      </style>
  </head>
<body>
  <header> 
  <div>  
<nav class="navbar navbar-default navbar-static-top">
  <div class="container" id="header-bg">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="home-title" class="navbar-brand" href="{}">BMNC Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="display: flex; flex-flow: row nowrap;">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a id="nav-profile" href="{% url 'berita:index' %}"> BMNC Project </a></li>
        <li><a id="nav-profile" href="{% url 'berita:index' %}"> Berita </a></li>
        <li><a id="nav-forum" href="{% url 'lihat-polling:index' %}"> Polling </a> </li>
        <li><a id="nav-forum" href="{% url 'profile:index' %}"> Profil </a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
</div>
</header>
  <content>
  <div class="pt-5 text-center">
    <div class="container">
      <h1 id="my-list-title" style = "padding-top: 1px;font-size: 35px;margin-left: 10px;margin-top: 5px;">Polling</h1>
        <hr>
      <div class="row">
        <div class="col-md-2 offset-md-4" style="margin-left: 300px;">
          <a class="btn btn-primary btn-block btn-lg m-2 w-100 py-2" id = 'polling-berita' href="{% url 'polling:buat_polling_berita' %}">
            <b>Polling Berita</b>
          </a>
        </div>
        <div class="col-md-2 offset-md-4" style="margin-left: 150px;">
          <a class="btn btn-primary btn-block btn-lg m-2 w-100 py-2" id = 'polling-biasa' href="{% url 'polling:buat_polling_biasa' %}" align="text-center">
            <b> Polling Biasa</b>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="">
    <div class="p-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="p-3 align-self-center col-md-4">
            <div class="card">
              <div class="card-block p-5">
                <h3>{{pertanyaan_polling}}</h3>
                <hr>
                <p>Polling Start: {{start_at}}</p>
                <p>Polling End: {{end_at}}</p>
                <a href="#" class="btn btn-dark">Go Vote</a>
              </div>
            </div>
          </div>
          <div class="p-3 align-self-center col-md-4">
            <div class="card">
              <div class="card-block p-5">
                <h3>{{pertanyaan_polling_1}}</h3>
                <hr>
                <p>Polling Start: {{start_at_1}}</p>
                <p>Polling End: {{end_at_1}}</p>
                <a href="#" class="btn btn-dark">Go Vote</a>
              </div>
            </div>
          </div>
          <div class="p-3 align-self-center col-md-4">
            <div class="card">
              <div class="card-block p-5">
                <h3>{{pertanyaan_polling_2}}</h3>
                <hr>
                <p>Polling Start: {{start_at_2}}</p>
                <p>Polling End: {{end_at_2}}</p>
                <a href="#" class="btn btn-dark">Go Vote</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </content>
  <footer>
        <center><p id="footer">&copy; Group 18 Basdat 2018-1 | Hardcode </p></center>
    </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>

</html>